import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Update the import path below to match the actual file location and casing, for example:
import NavbarWrapper from "../components/navbarwrapper";
import { AuthProvider } from "../context/authcontext";
import SessionProviderWrapper from "../components/sessionproviderwrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata (boleh kamu aktifkan kembali kalau perlu)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}